apiVersion: apps/v1
kind: Deployment
metadata: 
  name: headzone
  labels:
    app: headzone
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: headzone
  template:
    metadata:
      labels:
        app: headzone
    spec:
      containers:
        - name: headzone
          image: rahulchacko/headzone:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-port
---
apiVersion: v1
kind: Service
metadata:
  name: headzone-service
spec:
  selector:
    app: headzone
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
